/*
Всем привет.
Данная программа была написана под микроконтроллер ATTiny10 (4, 5, 9).
Программа выполняет сброс Dendy при помощи комбинации кнопок на джойстике.
Для работы программы необходимо перевести вывод PB3 в режим I/O, для этого нужно запрограммировать Fuse bit RSTDISBL.
Программа проверена на приставке с NTSC-чипами, с PAL-чипами не тестировалась.


Программа по умолчанию для приставок, где сброс осуществляется кнопкой, притягивающей вывод RES микросхемы PPU к земле питания. 
Если у Вас NES с CIC (3193a) чипом, то сброс осуществляется кнопкой, притягивающей вывод 7 CIC к плюсу питания. Я не тестировал данный режим, но если вы считаете? что понимаете, 
что делаете, то расскоментируйте строку ниже и пробуйте на NES с CIC. 
*/  

//.equ	NES	=	1

 

// Если хотите посмотреть в симуляторе МК, раскомментируйте строку ниже.
// Это ускорит прохождение чтения данных и отключит задержку сброса.

//.equ	SIMULATOR	=	1

// Выбор микроконтроллера:
.equ	ATtiny10	=	1
//.equ	ATtiny9	=	1
//.equ	ATtiny5	=	1
//.equ	ATtiny4	=	1

// Если вы используете беспроводной геймпад 8BitDo N30, раскомментируйте строку ниже, чтобы использовать кнопку Home для сброса Dendy. 
//.equ	J_8BitDo_N30	=	1

/*
Ниже задаём комбинацию кнопок джойстика для сброса Dendy (проверено только START & SELECT). 
Игнорируется если включён сброс кнопкой Home геймпада 8BitDo N30.
Кнопки: RIGHT, LEFT, DOWN, UP, START, SELECT, B, A.
Пример:
1. START & SELECT
2. START & SELECT & B
3. START & SELECT & UP
*/

.set	BUTTON_MASK = START & SELECT

/*
Ниже можно указать желаемое количество считываний комбинации кнопок до перехода к сбросу.
Можно добиться предотвращения ошибочных нажатий.
*/
.set	REPEAT = 10	//255 макс

// Сколько секунд ждать восстановления работы приставки до повторной перезагрузки.
// Избавляет от проблемы зависания приставки при нажатии кнопки сброса.

.set	REPTIME = 5	//255 макс

// Параметры разгона частоты 
.equ	stepOverClock = 4
.equ	stepOSCCAL = 20
.equ	delayStabil = 50
